name: MS-NEWS CI building and testing

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build job for ms-news
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # Checkout source code
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Here should be the chache
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        gradle-version: '9.0.0'

    # Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Run tests + JaCoCo + SonarQube
    # - name: Run Gradle tests and SonarQube
    #    run: gradle clean test --no-daemon
    #    run: gradle clean test jacocoTestReport sonarqube --no-daemon
    #   env:
    #      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    # Build with gradle
    - name: Build with Gradle 9.0.0
      run: gradle build

    

  
